name: CI Build

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.2.0
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
