# This is a basic workflow to help you get started with Actions

name: DOCKER TAGS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - release/dcs/v*
      - master
    tags:
      - v*-dcs

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: GITHUB_SHA
      run: echo ${GITHUB_SHA}

    - name: GITHUB_REF
      run: echo ${GITHUB_REF}

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"

    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: IS PRERELEASE
      if: "github.event.release.prerelease"
      run: echo "ONLY HERE IF RELEASE"

    - name: IS RELEASE
      if: "github.event.release"
      run: echo "ONLY HERE IF RELEASE"

    - name: IS RELEASE other way
      if: "github.event.release.prerelease"
      run: |
        echo "ONLY RELEASE other way"
        echo ${{ github.event.release.prerelease }}
        echo $pre_release
        echo $login
      env:
        pre_release: ${{ github.event.release.prerelease }}
        login: ${{ github.event.release.created_at }}

    - name: GITHUB_REF is TAG
      if: "contains(github.ref, 'tag')"
      run: echo ${GITHUB_REF}

    - name: GITHUB_REF is BRANCH
      if: "contains(github.ref, 'branch')"
      run: echo ${GITHUB_REF}

    - uses: nelonoel/branch-name@v1

    - name: DOCKER_TAG to branch name
      if: "github.ref == 'refs/heads/${BRANCH_NAME}'"
      run: echo "${BRANCH_NAME}"
    
    - name: DOCKER_TAG to tag name
      if: contains(github.ref, '/tags/')
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        echo "BRANCH=${BRANCH_NAME}"
        echo "TAG=${TAG_NAME}"
